apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: web-apps
spec:
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:      
      containers:
        - name: python-api
          image: ghcr.io/goncalvesj/k8s-arc-python-api:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          env:
            - name: APP_ENVIRONMENT
              value: "PROD"
            - name: PORT_REDIS
              value: "6379"
            - name: HOST_REDIS
              value: "my-redis-master"
            - name: PASSWORD_REDIS
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 60
          # livenessProbe:
          #   tcpSocket:
          #     port: 8080 
          #   initialDelaySeconds: 15 
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: web-apps
spec:
  selector:
    app: python-api
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8000
