trigger:
  branches:
    include:
    - master
  paths:
    include:
    - AppService-FrontDoor-PrivateEndpoints

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: cd AppService-FrontDoor-PrivateEndpoints

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --os linux --arch x64 -c $(buildConfiguration) -p:PublishProfile=DefaultContainer
  displayName: 'dotnet publish docker $(buildConfiguration)'