### Sender
GET http://localhost:5001/api/hello

### Service to Service
POST http://localhost:5001/api/service-to-service

### Pub Sub
POST http://localhost:5001/api/pub-sub

### Secret Store
GET http://localhost:5001/api/secret-store

### Consumer
GET http://localhost:5002/api/hello

###
POST http://localhost:5002/api/order
Content-Type: application/json
{
    "orderId": 1
}