apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-restapi
spec:
  selector:
    matchLabels:
      app: sw-restapi
  template:
    metadata:
      labels:
        app: sw-restapi
    spec:
      nodeSelector:
        pooltype: apps
        kubernetes.io/os: linux
      tolerations:
        - key: 'kubernetes.azure.com/scalesetpriority'
          operator: 'Equal'
          value: 'spot'
          effect: 'NoSchedule'
      containers:
        - name: sw-restapi
          image: ghcr.io/goncalvesj/sw-rest:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sw-restapi
spec:
  selector:
    app: sw-restapi
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 80