version: '3.4'

services:
  net.servicebus.worker:
    image:  net-servicebus-worker:dev
    environment:
     - SERVICEBUS_QUEUE_NAME=input     
     - SERVICEBUS_QUEUE_CONNECTIONSTRING=Endpoint=
     - STORAGE_CONNECTIONSTRING=DefaultEndpointsProtocol=
     - APPLICATIONINSIGHTS_CONNECTION_STRING=
     - PROCESSING_TIME_SECONDS=
    build:
      context: .
      dockerfile: Net.ServiceBus.Worker/Dockerfile

  net.servicebus.singlejob:
    image:  jprgacr.azurecr.io/net-servicebus-singlejob:dev
    environment:
     - SERVICEBUS_QUEUE_NAME=input-queue
     - SERVICEBUS_QUEUE_CONNECTIONSTRING=
     - STORAGE_CONNECTIONSTRING=
     - APPLICATIONINSIGHTS_CONNECTION_STRING=
    build:
      context: .
      dockerfile: Net.ServiceBus.SingleJob/Dockerfile