name: CI/CD - ADO and GH Sync

on:
  push:
    branches:
      - master
    paths:
      - "AzDevOps-GitHub-Workflow/**"
  workflow_dispatch:    

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: AzDevOps-GitHub-Workflow/Functions

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Scan .Net Function App
        uses: ./.github/actions/build-dotnet
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          configuration: ${{ env.CONFIGURATION }}
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: ${{ env.WORKING_DIRECTORY }}/output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: AzDevOps-GitHub-Workflow
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: ${{ env.WORKING_DIRECTORY }}/output

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:         
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'production'
          package: ${{ env.WORKING_DIRECTORY }}/output
