name: CI/CD - App Service Private Endpoints

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'AppService-FrontDoor-PrivateEndpoints/**'
      - '!AppService-FrontDoor-PrivateEndpoints/README.md'

env:
  DOTNET_CORE_VERSION: 9.0.x

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: AppService-FrontDoor-PrivateEndpoints/AppService-FrontDoor-PrivateEndpoints.sln

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}
      - name: Build
        run: dotnet build --no-restore ${{ env.SOLUTION_FILE }}
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_FILE }}

  deploy-to-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    outputs:
      new-tag: ${{ steps.publish.outputs.new-tag }}
    env:
      WORKING_DIRECTORY: AppService-FrontDoor-PrivateEndpoints
      IMAGE_NAME: dotnet-pe-tester
    steps:
      - name: Publish .Net App
        id: publish
        uses: goncalvesj/iac-templates/.github/actions/publish-dotnet-container@master
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          image-name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}