name: CI/CD - DotNet GraphQL Rest APIs

on:
  push:
    branches:
      - master
    paths:
      - 'DotNet-GraphQL-Rest-APIs/**'
      - '!DotNet-GraphQL-Rest-APIs/README.md'
  workflow_dispatch:

env:
  DOTNET_CORE_VERSION: 9.0.x

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: DotNet-GraphQL-Rest-APIs/API.sln

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}
      - name: Build
        run: dotnet build --no-restore ${{ env.SOLUTION_FILE }}
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_FILE }}

  deploy-rest-api-to-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    outputs:
      new-tag: ${{ steps.publish.outputs.new-tag }}
    env:
      WORKING_DIRECTORY: DotNet-GraphQL-Rest-APIs/Rest.API
      IMAGE_NAME: sw-rest
    steps:
      - name: Publish .Net App
        id: publish
        uses: goncalvesj/iac-templates/.github/actions/publish-dotnet-container@master
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          image-name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-graphql-api-to-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    outputs:
      new-tag: ${{ steps.publish.outputs.new-tag }}
    env:
      WORKING_DIRECTORY: DotNet-GraphQL-Rest-APIs/GraphQL.API
      IMAGE_NAME: sw-graphql
    steps:
      - name: Publish .Net App
        id: publish
        uses: goncalvesj/iac-templates/.github/actions/publish-dotnet-container@master
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          image-name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
