name: DotNet-GraphQL-Rest-APIs-Pipeline

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Testing'
  push:
    branches: [ master ]
    paths:
      - 'DotNet-GraphQL-Rest-APIs/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'DotNet-GraphQL-Rest-APIs/*'

env:
  GRAPHQL_IMAGE_NAME: "graphql-api"
  REST_IMAGE_NAME: "rest-api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    # - name: Lowercase the repo name and username
    #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    # - name: Build and push container image to registry
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
    #     file: ./DotNet-GraphQL-Rest-APIs/GraphQL.API/Dockerfile
    
    - name: Build the GraphQL Docker image
      run: |
        cd DotNet-GraphQL-Rest-APIs
        docker build . -f GraphQL.API/Dockerfile -t $GRAPHQL_IMAGE_NAME:$GITHUB_RUN_ID
        docker push $GRAPHQL_IMAGE_NAME:$GITHUB_RUN_ID

    # - name: Build the REST Docker image
    #   run: |
    #     cd DotNet-GraphQL-Rest-APIs
    #     docker build . -f Rest.API/Dockerfile -t $REST_IMAGE_NAME:$GITHUB_RUN_ID