name: Federated Identity CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'FederatedIdentity/FederatedIdentity.Web/**'
      - '.github/workflows/federated-identity.yml'
env:
  IMAGE_NAME: "federated-identity"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
      
    - name: Build the Docker image
      run: | 
       cd FederatedIdentity/FederatedIdentity.Web
       docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
      
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Push
      run: docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
