name: Trigger auto deployment for learnitall-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ features/es-spa ]
    paths:
    - '**'
    - '.github/workflows/learnitall-aca-AutoDeployTrigger-a7776dba-71a4-40dd-818e-198b52434c1b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jprgacr.azurecr.io
          username: ${{ secrets.LEARNITALLACA_REGISTRY_USERNAME }}
          password: ${{ secrets.LEARNITALLACA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jprgacr.azurecr.io/learnitall/demoapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LEARNITALLACA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n learnitall-aca -g LearnItAll-Serverless --server jprgacr.azurecr.io --username  ${{ secrets.LEARNITALLACA_REGISTRY_USERNAME }} --password ${{ secrets.LEARNITALLACA_REGISTRY_PASSWORD }}
            az containerapp update -n learnitall-aca -g LearnItAll-Serverless --image jprgacr.azurecr.io/learnitall/demoapp:${{ github.sha }}
