name: NetCore-Angular-B2C-CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Testing'
  push:
    branches:
      - master
    paths:
      - 'NetCore-Angular-AzureB2C/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'NetCore-Angular-AzureB2C/*'
      - '.github/workflows/netcore-angular-b2c.yml'

env:
  IMAGE_NAME: "netcore-angular-b2c"
  APP_CONTEXT: './NetCore-Angular-AzureB2C'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Build the Docker image
      run: |        
        docker buildx build $APP_CONTEXT -f $APP_CONTEXT/NetCore-Angular-AzureB2C/Dockerfile --output type=docker,dest=${{ env.REST_IMAGE_NAME }}.tar
