# This is a basic workflow to help you get started with Actions

name: NetCore-Angular-B2C-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  #DOCKERFILE_PATH: "/NetCore-Angular-AzureB2C/Dockerfile"
  IMAGE_NAME: "goncalvesj/netcore-angular-b2c"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Build the Docker image
    #  run: docker build . --file $GITHUB_WORKSPACE/$DOCKERFILE_PATH --tag $IMAGE_NAME:$GITHUB_RUN_ID
    
    - name: Build the Docker image
      run: |
        ls -R        
        cd NetCore-Angular-AzureB2C
        docker build . --file Dockerfile --tag $IMAGE_NAME:$GITHUB_RUN_ID
