name: PR - ADO and GH Sync

on:
  pull_request:
    branches:
      - master
    paths:
      - 'AzDevOps-GitHub-Workflow/**'

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AzDevOps-GitHub Environment
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Build Azure Function
      uses: ./.github/workflows/reusable-dotnet-build.yml   

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
