name: PR - ADO and GH Sync

on:
  pull_request:
    branches:
      - master
    paths:
      - "AzDevOps-GitHub-Workflow/**"

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: AzDevOps-GitHub-Workflow/Functions

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Scan .Net Function App
        uses: ./.github/actions/build-dotnet
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          configuration: ${{ env.CONFIGURATION }}
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
