name: PR - K8S On Azure Arc

on:
  push:
    branches:
      - master
    paths:
      - 'Azure-K8S-On-Arc/**'

env:
  APP_CONTEXT: 'Azure-K8S-On-Arc'

permissions:
  id-token: write
  contents: read

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - name: Build
        run: |
          cd ${{ env.APP_CONTEXT }}/node-api
          npm install
          npm run build

  build-python:
    runs-on: ubuntu-latest
    env:
      input: environment variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ${{ env.APP_CONTEXT }}/python-api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-dotnet:
    name: build dotnet api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Dapr Sender API
        uses: ./.github/actions/build-dotnet
        with:
          working-directory: Azure-K8S-On-Arc/dotnet-api
          configuration: Release
          dotnet-version: 8.0.x