name: PR - K8S On Azure Arc

on:
  push:
    branches:
      - master
    paths:
      - 'Azure-K8S-On-Arc/**'

env:
  APP_CONTEXT: 'Azure-K8S-On-Arc'

permissions:
  id-token: write
  contents: read

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      
      - name: Build
        run: |
          cd ${{ env.APP_CONTEXT }}/node-api
          npm install
          npm run build
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build-python:
    runs-on: ubuntu-latest
    env:
      input: environment variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Build
        run: |
          cd ${{ env.APP_CONTEXT }}/python-api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build-dotnet:
    name: build dotnet api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      
      - name: Build
        run: |
          cd ${{ env.APP_CONTEXT }}/dotnet-api
          dotnet restore
          dotnet build
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2