name: Reusable - Push to Azure Container Registry

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      build-context:
        required: true
        type: string
      dockerfile-location:
        required: true
        type: string

permissions: read-all
jobs:
  push-to-acr:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure ACR Login
        run: |
          az acr login -n ${{ secrets.AZURE_ACR_NAME }}

      - name: Build the Docker image
        run: |
          cd ${{ inputs.build-context }}
          docker build -f ${{ inputs.dockerfile-location }} \
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ inputs.image-tag }}:$GITHUB_RUN_ID \
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ inputs.image-tag }}:latest .

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ inputs.image-tag }}:$GITHUB_RUN_ID
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ inputs.image-tag }}:latest
