name: Reusable - Push to GitHub Container Registry

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      build-context:
        required: true
        type: string
      dockerfile-location:
        required: true
        type: string

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image
        run: |
          cd ${{ inputs.build-context }}
          docker buildx build -f ${{ inputs.dockerfile-location }} \
          --push \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.actor }}/${{ inputs.image-tag }}:$GITHUB_RUN_ID \
          -t ghcr.io/${{ github.actor }}/${{ inputs.image-tag }}:latest .   

      # - name: Push the Docker image
      #   run: |          
      #     docker push ghcr.io/${{ github.actor }}/${{ inputs.image-tag }}:$GITHUB_RUN_ID
      #     docker push ghcr.io/${{ github.actor }}/${{ inputs.image-tag }}:latest
