name: Reusable - Build DotNet

on:
  workflow_call:

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    environment: AzDevOps-GitHub Environment
    steps:
      - name: Restore
        run: dotnet restore "${{ vars.WORKING_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ vars.WORKING_DIRECTORY }}" --configuration ${{ vars.CONFIGURATION }} --no-restore
      - name: Publish
        run: dotnet publish "${{ vars.WORKING_DIRECTORY }}" --configuration ${{ vars.CONFIGURATION }} --no-build --output "${{ vars.WORKING_DIRECTORY }}"
  